/*
 * sabian.js — サビアンシンボル360度データ
 * data/sabian_symbols_en.json から生成。ja が null の間は英語を表示。
 * ja欄はみっちゃんが自分のメモで埋めていくスロット（data/sabian_symbols_ja_notes.json 経由で再生成可）。
 * キー: 絶対度数 1..360（牡羊座1度=1）。degree = サイン内サビアン度数（1..30）。
 * ★2026-07-22: 旧データは360度中198度が誤り（別度数の象徴が混入）だったため、
 *   公有の正典（Marc Edmund Jones / Dane Rudhyar 系の一行シンボル）と照合し全面再構築。
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) { module.exports = factory(); }
  else { root.SABIAN = factory(); }
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";
  return {
    1: { sign: "Aries", degree: 1, en: "A woman has risen out of the ocean, a seal is embracing her", ja: null },
    2: { sign: "Aries", degree: 2, en: "A comedian entertaining the group", ja: null },
    3: { sign: "Aries", degree: 3, en: "A cameo profile of a man in the outline of his country", ja: null },
    4: { sign: "Aries", degree: 4, en: "Two lovers strolling through a secluded walk", ja: null },
    5: { sign: "Aries", degree: 5, en: "A triangle with wings", ja: null },
    6: { sign: "Aries", degree: 6, en: "A square brightly lighted on one side", ja: null },
    7: { sign: "Aries", degree: 7, en: "A man successfully expressing himself in two realms at once", ja: null },
    8: { sign: "Aries", degree: 8, en: "A woman's hat with streamers blown by the east wind", ja: null },
    9: { sign: "Aries", degree: 9, en: "A crystal gazer", ja: null },
    10: { sign: "Aries", degree: 10, en: "A teacher gives new symbolic forms to traditional images", ja: null },
    11: { sign: "Aries", degree: 11, en: "The ruler of a nation", ja: null },
    12: { sign: "Aries", degree: 12, en: "A flock of wild geese", ja: null },
    13: { sign: "Aries", degree: 13, en: "A bomb which failed to explode is now safely concealed", ja: null },
    14: { sign: "Aries", degree: 14, en: "A serpent coiling near a man and a woman", ja: null },
    15: { sign: "Aries", degree: 15, en: "An Indian weaving a blanket", ja: null },
    16: { sign: "Aries", degree: 16, en: "Brownies dancing in the setting sun", ja: null },
    17: { sign: "Aries", degree: 17, en: "Two prim spinsters sitting together in silence", ja: null },
    18: { sign: "Aries", degree: 18, en: "An empty hammock", ja: null },
    19: { sign: "Aries", degree: 19, en: "The magic carpet of oriental imagery", ja: null },
    20: { sign: "Aries", degree: 20, en: "A young girl feeding birds in winter", ja: null },
    21: { sign: "Aries", degree: 21, en: "A pugilist entering the ring", ja: null },
    22: { sign: "Aries", degree: 22, en: "The gate to the garden of all fulfilled desires", ja: null },
    23: { sign: "Aries", degree: 23, en: "A woman in pastel colors carrying a heavy and valuable but veiled load", ja: null },
    24: { sign: "Aries", degree: 24, en: "An open window and a net curtain blowing into a cornucopia", ja: null },
    25: { sign: "Aries", degree: 25, en: "A double promise reveals its inner and outer meanings", ja: null },
    26: { sign: "Aries", degree: 26, en: "A man possessed of more gifts than he can hold", ja: null },
    27: { sign: "Aries", degree: 27, en: "Through imagination, a lost opportunity is regained", ja: null },
    28: { sign: "Aries", degree: 28, en: "A large disappointed audience", ja: null },
    29: { sign: "Aries", degree: 29, en: "The music of the spheres", ja: null },
    30: { sign: "Aries", degree: 30, en: "A duck pond and its brood", ja: null },
    31: { sign: "Taurus", degree: 1, en: "A clear mountain stream", ja: null },
    32: { sign: "Taurus", degree: 2, en: "An electrical storm", ja: null },
    33: { sign: "Taurus", degree: 3, en: "Steps up to a lawn blooming with clover", ja: null },
    34: { sign: "Taurus", degree: 4, en: "The pot of gold at the end of the rainbow", ja: null },
    35: { sign: "Taurus", degree: 5, en: "A widow at an open grave", ja: null },
    36: { sign: "Taurus", degree: 6, en: "A bridge being built across a gorge", ja: null },
    37: { sign: "Taurus", degree: 7, en: "A woman of Samaria comes to draw water from the well", ja: null },
    38: { sign: "Taurus", degree: 8, en: "A sleigh without snow", ja: null },
    39: { sign: "Taurus", degree: 9, en: "A Christmas tree decorated", ja: null },
    40: { sign: "Taurus", degree: 10, en: "A red cross nurse", ja: null },
    41: { sign: "Taurus", degree: 11, en: "A woman sprinkling flowers", ja: null },
    42: { sign: "Taurus", degree: 12, en: "A young couple walk down main-street, window-shopping", ja: null },
    43: { sign: "Taurus", degree: 13, en: "A porter carrying heavy baggage", ja: null },
    44: { sign: "Taurus", degree: 14, en: "On the beach, children play while shellfish grope at the edge of the water", ja: null },
    45: { sign: "Taurus", degree: 15, en: "A man with rakish silk hat, muffled against the cold, braves a storm", ja: null },
    46: { sign: "Taurus", degree: 16, en: "An old teacher fails to interest his pupils in traditional knowledge", ja: null },
    47: { sign: "Taurus", degree: 17, en: "A symbolical battle between swords and torches", ja: null },
    48: { sign: "Taurus", degree: 18, en: "A woman airing an old bag through a sunny window", ja: null },
    49: { sign: "Taurus", degree: 19, en: "A new continent rising out of the ocean", ja: null },
    50: { sign: "Taurus", degree: 20, en: "Wisps of clouds, like wings, are streaming across the sky", ja: null },
    51: { sign: "Taurus", degree: 21, en: "Moving finger points to significant passages in a book", ja: null },
    52: { sign: "Taurus", degree: 22, en: "White dove flying over troubled waters", ja: null },
    53: { sign: "Taurus", degree: 23, en: "A jewellery shop filled with the most magnificent jewels", ja: null },
    54: { sign: "Taurus", degree: 24, en: "An Indian warrior riding fiercely, human scalps hanging at his belt", ja: null },
    55: { sign: "Taurus", degree: 25, en: "A large well-kept public park", ja: null },
    56: { sign: "Taurus", degree: 26, en: "A Spaniard serenading his senorita", ja: null },
    57: { sign: "Taurus", degree: 27, en: "An old Indian woman selling beads", ja: null },
    58: { sign: "Taurus", degree: 28, en: "A mature woman reawakened to romance", ja: null },
    59: { sign: "Taurus", degree: 29, en: "Two cobblers working at a table", ja: null },
    60: { sign: "Taurus", degree: 30, en: "A peacock parading on the terrace of an old castle", ja: null },
    61: { sign: "Gemini", degree: 1, en: "A glass-bottomed boat reveals under-sea wonders", ja: null },
    62: { sign: "Gemini", degree: 2, en: "Santa Claus filling stockings furtively", ja: null },
    63: { sign: "Gemini", degree: 3, en: "The garden of the Tuileries in Paris", ja: null },
    64: { sign: "Gemini", degree: 4, en: "Holly and mistletoe bring Christmas spirit to a home", ja: null },
    65: { sign: "Gemini", degree: 5, en: "A radical magazine, asking for action, displays a sensational front page", ja: null },
    66: { sign: "Gemini", degree: 6, en: "Workmen drilling for oil", ja: null },
    67: { sign: "Gemini", degree: 7, en: "An old-fashioned well", ja: null },
    68: { sign: "Gemini", degree: 8, en: "Aroused strikers round a factory", ja: null },
    69: { sign: "Gemini", degree: 9, en: "A quiver filled with arrows", ja: null },
    70: { sign: "Gemini", degree: 10, en: "Aeroplane performing a nose-dive", ja: null },
    71: { sign: "Gemini", degree: 11, en: "Newly opened lands offer the pioneer new opportunities for experience", ja: null },
    72: { sign: "Gemini", degree: 12, en: "A black slave-girl demands her rights of her mistress", ja: null },
    73: { sign: "Gemini", degree: 13, en: "World famous pianist giving a concert performance", ja: null },
    74: { sign: "Gemini", degree: 14, en: "Two people, living far apart, in telepathic communication", ja: null },
    75: { sign: "Gemini", degree: 15, en: "Two Dutch children talking", ja: null },
    76: { sign: "Gemini", degree: 16, en: "A woman activist in an emotional speech, dramatizing her cause", ja: null },
    77: { sign: "Gemini", degree: 17, en: "The head of a robust youth changes into that of a mature thinker", ja: null },
    78: { sign: "Gemini", degree: 18, en: "Two Chinese men talking Chinese in a western crowd", ja: null },
    79: { sign: "Gemini", degree: 19, en: "A large archaic volume reveals a traditional wisdom", ja: null },
    80: { sign: "Gemini", degree: 20, en: "A cafeteria with an abundance of choices", ja: null },
    81: { sign: "Gemini", degree: 21, en: "A tumultuous labor demonstration", ja: null },
    82: { sign: "Gemini", degree: 22, en: "Dancing couples crowd the barn in a harvest festival", ja: null },
    83: { sign: "Gemini", degree: 23, en: "Three fledglings in a nest high in a tree", ja: null },
    84: { sign: "Gemini", degree: 24, en: "Children skating on ice", ja: null },
    85: { sign: "Gemini", degree: 25, en: "A gardener trimming large palm trees", ja: null },
    86: { sign: "Gemini", degree: 26, en: "Winter frost in the woods", ja: null },
    87: { sign: "Gemini", degree: 27, en: "A young gypsy emerging from the woods gazes at far cities", ja: null },
    88: { sign: "Gemini", degree: 28, en: "Society granting bankruptcy to him, a man leaves the court", ja: null },
    89: { sign: "Gemini", degree: 29, en: "The first mockingbird of spring sings from the tree top", ja: null },
    90: { sign: "Gemini", degree: 30, en: "A parade of bathing beauties before large beach crowds", ja: null },
    91: { sign: "Cancer", degree: 1, en: "On a ship the sailors lower an old flag and raise a new one", ja: null },
    92: { sign: "Cancer", degree: 2, en: "A man on a magic carpet observes vast vistas below him", ja: null },
    93: { sign: "Cancer", degree: 3, en: "An Arctic explorer leads a reindeer through icy canyons", ja: null },
    94: { sign: "Cancer", degree: 4, en: "A cat arguing with a mouse", ja: null },
    95: { sign: "Cancer", degree: 5, en: "At a railroad crossing, an automobile is wrecked by a train", ja: null },
    96: { sign: "Cancer", degree: 6, en: "Game birds feathering their nests", ja: null },
    97: { sign: "Cancer", degree: 7, en: "Two fairies dancing on a moonlit night", ja: null },
    98: { sign: "Cancer", degree: 8, en: "A group of rabbits dressed in clothes and on parade", ja: null },
    99: { sign: "Cancer", degree: 9, en: "A small, naked girl bends over a pond trying to catch a fish", ja: null },
    100: { sign: "Cancer", degree: 10, en: "A large diamond in the first stages of the cutting process", ja: null },
    101: { sign: "Cancer", degree: 11, en: "A clown caricaturing well-known personalities", ja: null },
    102: { sign: "Cancer", degree: 12, en: "A Chinese woman nursing a baby whose aura reveals him to be the reincarnation of a great teacher", ja: null },
    103: { sign: "Cancer", degree: 13, en: "One hand slightly flexed with a very prominent thumb", ja: null },
    104: { sign: "Cancer", degree: 14, en: "A very old man facing a vast dark space to the northeast", ja: null },
    105: { sign: "Cancer", degree: 15, en: "A group of people who have overeaten and enjoyed it", ja: null },
    106: { sign: "Cancer", degree: 16, en: "A man studying a mandala in front of him, with the help of a very ancient book", ja: null },
    107: { sign: "Cancer", degree: 17, en: "The seed grows into knowledge and life", ja: null },
    108: { sign: "Cancer", degree: 18, en: "A hen scratching for her chicks", ja: null },
    109: { sign: "Cancer", degree: 19, en: "A priest performing a marriage ceremony", ja: null },
    110: { sign: "Cancer", degree: 20, en: "Venetian gondoliers in a serenade", ja: null },
    111: { sign: "Cancer", degree: 21, en: "A prima donna singing", ja: null },
    112: { sign: "Cancer", degree: 22, en: "A young woman awaiting a sailboat", ja: null },
    113: { sign: "Cancer", degree: 23, en: "The meeting of a literary society", ja: null },
    114: { sign: "Cancer", degree: 24, en: "A woman and two men castaways on a small island of the south seas", ja: null },
    115: { sign: "Cancer", degree: 25, en: "A leader of men wrapped in an invisible mantle of power", ja: null },
    116: { sign: "Cancer", degree: 26, en: "Guests are reading in the library of a luxurious home", ja: null },
    117: { sign: "Cancer", degree: 27, en: "A violent storm in a canyon filled with expensive homes", ja: null },
    118: { sign: "Cancer", degree: 28, en: "Indian girl introduces college boy-friend to her assembled tribe", ja: null },
    119: { sign: "Cancer", degree: 29, en: "A Greek muse weighing new born twins in golden scales", ja: null },
    120: { sign: "Cancer", degree: 30, en: "A daughter of the American revolution", ja: null },
    121: { sign: "Leo", degree: 1, en: "Under emotional stress, blood rushes to a man's head", ja: null },
    122: { sign: "Leo", degree: 2, en: "An epidemic of mumps", ja: null },
    123: { sign: "Leo", degree: 3, en: "A mature woman, keeping up with the times, having her hair bobbed", ja: null },
    124: { sign: "Leo", degree: 4, en: "A man formally dressed stands near trophies he brought back from a hunting expedition", ja: null },
    125: { sign: "Leo", degree: 5, en: "Rock formations tower over a deep canyon", ja: null },
    126: { sign: "Leo", degree: 6, en: "An old fashioned conservative woman is confronted by an up-to-date girl", ja: null },
    127: { sign: "Leo", degree: 7, en: "The constellations of stars in the sky", ja: null },
    128: { sign: "Leo", degree: 8, en: "A communist activist spreading his revolutionary ideals", ja: null },
    129: { sign: "Leo", degree: 9, en: "Glass blowers shape beautiful vases with their controlled breathing", ja: null },
    130: { sign: "Leo", degree: 10, en: "Early morning dew", ja: null },
    131: { sign: "Leo", degree: 11, en: "Children on a swing in a huge oak tree", ja: null },
    132: { sign: "Leo", degree: 12, en: "An evening lawn party of adults", ja: null },
    133: { sign: "Leo", degree: 13, en: "An old sea captain rocking on the porch of his cottage", ja: null },
    134: { sign: "Leo", degree: 14, en: "Cherub-like, a human soul whispers, seeking to manifest", ja: null },
    135: { sign: "Leo", degree: 15, en: "A pageant moving along a street packed with people", ja: null },
    136: { sign: "Leo", degree: 16, en: "Brilliant sunshine just after a storm", ja: null },
    137: { sign: "Leo", degree: 17, en: "Volunteer church choir makes social event of rehearsal", ja: null },
    138: { sign: "Leo", degree: 18, en: "A chemist conducts an experiment for his students", ja: null },
    139: { sign: "Leo", degree: 19, en: "A houseboat party", ja: null },
    140: { sign: "Leo", degree: 20, en: "American Indians perform a ritual to the sun", ja: null },
    141: { sign: "Leo", degree: 21, en: "Intoxicated chickens dizzily flap their wings trying to fly", ja: null },
    142: { sign: "Leo", degree: 22, en: "A carrier pigeon fulfilling its mission", ja: null },
    143: { sign: "Leo", degree: 23, en: "A bareback rider in a circus displays her dangerous skill", ja: null },
    144: { sign: "Leo", degree: 24, en: "A man sitting in complete neglect of his body, concentrated on inner spiritual attainment", ja: null },
    145: { sign: "Leo", degree: 25, en: "A large camel crossing a vast and forbidding desert", ja: null },
    146: { sign: "Leo", degree: 26, en: "After a heavy storm, a rainbow", ja: null },
    147: { sign: "Leo", degree: 27, en: "Daybreak, the luminescence of dawn in the eastern sky", ja: null },
    148: { sign: "Leo", degree: 28, en: "Many little birds on the limb of a large tree", ja: null },
    149: { sign: "Leo", degree: 29, en: "A mermaid emerges from the ocean ready for rebirth in human form", ja: null },
    150: { sign: "Leo", degree: 30, en: "An unsealed letter", ja: null },
    151: { sign: "Virgo", degree: 1, en: "In a portrait the best of a man's features and traits are idealized", ja: null },
    152: { sign: "Virgo", degree: 2, en: "A large white cross dominating the landscape stands alone on top of a high hill", ja: null },
    153: { sign: "Virgo", degree: 3, en: "Two guardian angels bringing protection", ja: null },
    154: { sign: "Virgo", degree: 4, en: "Black and white children playing happily together", ja: null },
    155: { sign: "Virgo", degree: 5, en: "A man becoming aware of nature spirits and normally unseen spiritual energies", ja: null },
    156: { sign: "Virgo", degree: 6, en: "A merry-go-round", ja: null },
    157: { sign: "Virgo", degree: 7, en: "A harem", ja: null },
    158: { sign: "Virgo", degree: 8, en: "A girl takes her first dancing instruction", ja: null },
    159: { sign: "Virgo", degree: 9, en: "An expressionist painter making a futuristic drawing", ja: null },
    160: { sign: "Virgo", degree: 10, en: "Two heads looking out and beyond the shadows", ja: null },
    161: { sign: "Virgo", degree: 11, en: "A boy moulded in his mother's aspirations for him", ja: null },
    162: { sign: "Virgo", degree: 12, en: "A bride with her veil snatched away", ja: null },
    163: { sign: "Virgo", degree: 13, en: "A powerful statesman overcomes a state of political hysteria", ja: null },
    164: { sign: "Virgo", degree: 14, en: "A family tree", ja: null },
    165: { sign: "Virgo", degree: 15, en: "A fine lace ornamental handkerchief", ja: null },
    166: { sign: "Virgo", degree: 16, en: "Children crowd around the orang-utang cage in a zoo", ja: null },
    167: { sign: "Virgo", degree: 17, en: "A volcanic eruption", ja: null },
    168: { sign: "Virgo", degree: 18, en: "Two girls playing with a ouija board", ja: null },
    169: { sign: "Virgo", degree: 19, en: "A swimming race", ja: null },
    170: { sign: "Virgo", degree: 20, en: "A caravan of cars headed for promised lands", ja: null },
    171: { sign: "Virgo", degree: 21, en: "A girl's basketball team", ja: null },
    172: { sign: "Virgo", degree: 22, en: "A royal coat of arms enriched with precious stones", ja: null },
    173: { sign: "Virgo", degree: 23, en: "A lion-tamer rushes fearlessly into the circus arena", ja: null },
    174: { sign: "Virgo", degree: 24, en: "Mary and her white lamb", ja: null },
    175: { sign: "Virgo", degree: 25, en: "A flag at half-mast in front of a public building", ja: null },
    176: { sign: "Virgo", degree: 26, en: "A boy with a censer serves near the priest at the altar", ja: null },
    177: { sign: "Virgo", degree: 27, en: "Aristocratic elderly ladies drinking afternoon tea in a wealthy home", ja: null },
    178: { sign: "Virgo", degree: 28, en: "A bald-headed man who has seized power", ja: null },
    179: { sign: "Virgo", degree: 29, en: "A man gaining secret knowledge from an ancient scroll he is reading", ja: null },
    180: { sign: "Virgo", degree: 30, en: "Having an urgent task to complete, a man doesn't look to any distractions", ja: null },
    181: { sign: "Libra", degree: 1, en: "A butterfly preserved and made perfect with a dart through it", ja: null },
    182: { sign: "Libra", degree: 2, en: "The light of the sixth race transmuted to the seventh", ja: null },
    183: { sign: "Libra", degree: 3, en: "The dawn of a new day reveals everything changed", ja: null },
    184: { sign: "Libra", degree: 4, en: "A group of young people sit in spiritual communion around a campfire", ja: null },
    185: { sign: "Libra", degree: 5, en: "A man teaching the true inner knowledge of the new world to his students", ja: null },
    186: { sign: "Libra", degree: 6, en: "A man watches his ideals taking a concrete form before his inner vision", ja: null },
    187: { sign: "Libra", degree: 7, en: "A woman feeding chickens and protecting them from the hawks", ja: null },
    188: { sign: "Libra", degree: 8, en: "A blazing fireplace in a deserted home", ja: null },
    189: { sign: "Libra", degree: 9, en: "Three old masters hanging in a special room in an art gallery", ja: null },
    190: { sign: "Libra", degree: 10, en: "A canoe approaching safety through dangerous waters", ja: null },
    191: { sign: "Libra", degree: 11, en: "A professor peering over his glasses at his students", ja: null },
    192: { sign: "Libra", degree: 12, en: "Miners are emerging from a deep coal mine", ja: null },
    193: { sign: "Libra", degree: 13, en: "Children blowing soap bubbles", ja: null },
    194: { sign: "Libra", degree: 14, en: "In the heat of the noon, a man takes a siesta", ja: null },
    195: { sign: "Libra", degree: 15, en: "Circular paths", ja: null },
    196: { sign: "Libra", degree: 16, en: "After a storm, a boat landing stands in need of reconstruction", ja: null },
    197: { sign: "Libra", degree: 17, en: "A retired sea captain watches ships entering and leaving the harbour", ja: null },
    198: { sign: "Libra", degree: 18, en: "Two men placed under arrest", ja: null },
    199: { sign: "Libra", degree: 19, en: "A gang of robbers in hiding", ja: null },
    200: { sign: "Libra", degree: 20, en: "A Jewish rabbi performing his duties", ja: null },
    201: { sign: "Libra", degree: 21, en: "A crowd upon a beach", ja: null },
    202: { sign: "Libra", degree: 22, en: "A child giving birds a drink at a fountain", ja: null },
    203: { sign: "Libra", degree: 23, en: "Chanticleer's voice heralds the rising sun with exuberant tones", ja: null },
    204: { sign: "Libra", degree: 24, en: "A third wing on the left side of a butterfly", ja: null },
    205: { sign: "Libra", degree: 25, en: "The sight of an autumn leaf brings to a pilgrim the sudden revelation of the mystery of life and death", ja: null },
    206: { sign: "Libra", degree: 26, en: "An eagle and a large white dove turning into each other", ja: null },
    207: { sign: "Libra", degree: 27, en: "An airplane sails, high in the clear sky", ja: null },
    208: { sign: "Libra", degree: 28, en: "A man in deep gloom. Unnoticed, angels come to his help", ja: null },
    209: { sign: "Libra", degree: 29, en: "Mankind's vast enduring effort to reach for knowledge transferable from generation to generation", ja: null },
    210: { sign: "Libra", degree: 30, en: "Three mounds of knowledge on a philosopher's head", ja: null },
    211: { sign: "Scorpio", degree: 1, en: "A sight-seeing bus filled with tourists", ja: null },
    212: { sign: "Scorpio", degree: 2, en: "A broken bottle and spilled perfume", ja: null },
    213: { sign: "Scorpio", degree: 3, en: "Neighbours help in a house-raising party in a small village", ja: null },
    214: { sign: "Scorpio", degree: 4, en: "A youth holding a lighted candle in a devotional ritual", ja: null },
    215: { sign: "Scorpio", degree: 5, en: "A massive, rocky shore resists the pounding of the sea", ja: null },
    216: { sign: "Scorpio", degree: 6, en: "A gold rush tears men away from their native soil", ja: null },
    217: { sign: "Scorpio", degree: 7, en: "Deep-sea divers", ja: null },
    218: { sign: "Scorpio", degree: 8, en: "The moon shining across a lake", ja: null },
    219: { sign: "Scorpio", degree: 9, en: "A dentist at work", ja: null },
    220: { sign: "Scorpio", degree: 10, en: "A fellowship supper reunites old comrades", ja: null },
    221: { sign: "Scorpio", degree: 11, en: "A drowning man is being rescued", ja: null },
    222: { sign: "Scorpio", degree: 12, en: "An official embassy ball", ja: null },
    223: { sign: "Scorpio", degree: 13, en: "An inventor performs a laboratory experiment", ja: null },
    224: { sign: "Scorpio", degree: 14, en: "Telephone linemen at work installing new connections", ja: null },
    225: { sign: "Scorpio", degree: 15, en: "Children playing around five mounds of sand", ja: null },
    226: { sign: "Scorpio", degree: 16, en: "A girl's face breaking into a smile", ja: null },
    227: { sign: "Scorpio", degree: 17, en: "A woman, filled with her own spirit, is the father of her own child", ja: null },
    228: { sign: "Scorpio", degree: 18, en: "A path through woods rich in autumn coloring", ja: null },
    229: { sign: "Scorpio", degree: 19, en: "A parrot listening and then talking, repeats a conversation he has overheard", ja: null },
    230: { sign: "Scorpio", degree: 20, en: "A woman drawing aside two dark curtains that closed the entrance to a sacred pathway", ja: null },
    231: { sign: "Scorpio", degree: 21, en: "Obeying his conscience, a soldier resists orders", ja: null },
    232: { sign: "Scorpio", degree: 22, en: "Hunters shooting wild ducks", ja: null },
    233: { sign: "Scorpio", degree: 23, en: "A rabbit metamorphosed into a fairy", ja: null },
    234: { sign: "Scorpio", degree: 24, en: "Crowds coming down the mountain to listen to one inspired man", ja: null },
    235: { sign: "Scorpio", degree: 25, en: "An x-ray photograph", ja: null },
    236: { sign: "Scorpio", degree: 26, en: "Indians making camp in new territory", ja: null },
    237: { sign: "Scorpio", degree: 27, en: "A military band marches noisily on through the city streets", ja: null },
    238: { sign: "Scorpio", degree: 28, en: "The king of the fairies approaching his domain", ja: null },
    239: { sign: "Scorpio", degree: 29, en: "An Indian woman pleading to the chief for the lives of her children", ja: null },
    240: { sign: "Scorpio", degree: 30, en: "Children in Halloween costumes indulging in various pranks", ja: null },
    241: { sign: "Sagittarius", degree: 1, en: "Retired army veterans gather to reawaken old memories", ja: null },
    242: { sign: "Sagittarius", degree: 2, en: "The ocean covered with whitecaps", ja: null },
    243: { sign: "Sagittarius", degree: 3, en: "Two men playing chess", ja: null },
    244: { sign: "Sagittarius", degree: 4, en: "A little child learning to walk", ja: null },
    245: { sign: "Sagittarius", degree: 5, en: "An old owl up in a tree", ja: null },
    246: { sign: "Sagittarius", degree: 6, en: "A game of cricket", ja: null },
    247: { sign: "Sagittarius", degree: 7, en: "Cupid knocking at the door of a human heart", ja: null },
    248: { sign: "Sagittarius", degree: 8, en: "Deep within the depths of the earth, new elements are being formed", ja: null },
    249: { sign: "Sagittarius", degree: 9, en: "A mother leads her small child step by step up the stairs", ja: null },
    250: { sign: "Sagittarius", degree: 10, en: "A theatrical representation of a golden haired goddess of opportunity", ja: null },
    251: { sign: "Sagittarius", degree: 11, en: "The lamp of physical enlightenment at the left temple", ja: null },
    252: { sign: "Sagittarius", degree: 12, en: "A flag that turns into an eagle that crows", ja: null },
    253: { sign: "Sagittarius", degree: 13, en: "A widow's past is brought to light", ja: null },
    254: { sign: "Sagittarius", degree: 14, en: "The pyramids and the sphinx", ja: null },
    255: { sign: "Sagittarius", degree: 15, en: "The ground hog looking for its shadow on ground hog day", ja: null },
    256: { sign: "Sagittarius", degree: 16, en: "Sea gulls fly around a ship looking for food", ja: null },
    257: { sign: "Sagittarius", degree: 17, en: "An Easter sunrise service", ja: null },
    258: { sign: "Sagittarius", degree: 18, en: "Tiny children in sunbonnets", ja: null },
    259: { sign: "Sagittarius", degree: 19, en: "Pelicans, disturbed by the garbage of people, move their young to a new habitat", ja: null },
    260: { sign: "Sagittarius", degree: 20, en: "In winter people cutting ice from a frozen pond, for summer use", ja: null },
    261: { sign: "Sagittarius", degree: 21, en: "A child and a dog wearing borrowed eyeglasses", ja: null },
    262: { sign: "Sagittarius", degree: 22, en: "A Chinese laundry", ja: null },
    263: { sign: "Sagittarius", degree: 23, en: "Immigrants entering a new country", ja: null },
    264: { sign: "Sagittarius", degree: 24, en: "A bluebird standing at the door of the house", ja: null },
    265: { sign: "Sagittarius", degree: 25, en: "A chubby boy on a hobbyhorse", ja: null },
    266: { sign: "Sagittarius", degree: 26, en: "A flag-bearer in a battle", ja: null },
    267: { sign: "Sagittarius", degree: 27, en: "The sculptor's vision is taking form", ja: null },
    268: { sign: "Sagittarius", degree: 28, en: "An old bridge over a beautiful stream in constant use", ja: null },
    269: { sign: "Sagittarius", degree: 29, en: "A fat boy mowing the lawn", ja: null },
    270: { sign: "Sagittarius", degree: 30, en: "The pope blessing the faithful", ja: null },
    271: { sign: "Capricorn", degree: 1, en: "An Indian chief claims power from the assembled tribe", ja: null },
    272: { sign: "Capricorn", degree: 2, en: "Three stained-glass windows in a Gothic church, one damaged by war", ja: null },
    273: { sign: "Capricorn", degree: 3, en: "The human soul, in its eagerness for new experiences, seeks embodiment", ja: null },
    274: { sign: "Capricorn", degree: 4, en: "A group of people entering a large canoe for a journey by water", ja: null },
    275: { sign: "Capricorn", degree: 5, en: "Indians, some rowing a canoe and others dancing a war dance in it", ja: null },
    276: { sign: "Capricorn", degree: 6, en: "Ten logs lie under an archway leading to darker woods", ja: null },
    277: { sign: "Capricorn", degree: 7, en: "A veiled prophet speaks, seized by the power of a god", ja: null },
    278: { sign: "Capricorn", degree: 8, en: "Birds in the house singing happily", ja: null },
    279: { sign: "Capricorn", degree: 9, en: "An angel carrying a harp", ja: null },
    280: { sign: "Capricorn", degree: 10, en: "An albatross feeding from the hand of a sailor", ja: null },
    281: { sign: "Capricorn", degree: 11, en: "Pheasants display their brilliant colors on a private estate", ja: null },
    282: { sign: "Capricorn", degree: 12, en: "A student of nature lecturing, revealing little-known aspects of life", ja: null },
    283: { sign: "Capricorn", degree: 13, en: "A fire worshipper meditates on the ultimate realities of existence", ja: null },
    284: { sign: "Capricorn", degree: 14, en: "An ancient bas-relief carved in granite remains a witness to a long-forgotten culture", ja: null },
    285: { sign: "Capricorn", degree: 15, en: "In a hospital, the children's ward is filled with toys", ja: null },
    286: { sign: "Capricorn", degree: 16, en: "School grounds filled with boys and girls in gymnasium suits", ja: null },
    287: { sign: "Capricorn", degree: 17, en: "A girl surreptitiously bathing in the nude", ja: null },
    288: { sign: "Capricorn", degree: 18, en: "The Union Jack flies from a new British warship", ja: null },
    289: { sign: "Capricorn", degree: 19, en: "A child of about five carrying a huge shopping bag filled with groceries", ja: null },
    290: { sign: "Capricorn", degree: 20, en: "A hidden choir singing during a religious service", ja: null },
    291: { sign: "Capricorn", degree: 21, en: "A relay race", ja: null },
    292: { sign: "Capricorn", degree: 22, en: "A general accepting defeat gracefully", ja: null },
    293: { sign: "Capricorn", degree: 23, en: "A soldier receiving two awards for bravery in combat", ja: null },
    294: { sign: "Capricorn", degree: 24, en: "A woman entering a convent", ja: null },
    295: { sign: "Capricorn", degree: 25, en: "An oriental rug dealer in a store filled with precious ornamental rugs", ja: null },
    296: { sign: "Capricorn", degree: 26, en: "A nature spirit dancing in the mist of a waterfall", ja: null },
    297: { sign: "Capricorn", degree: 27, en: "A mountain pilgrimage", ja: null },
    298: { sign: "Capricorn", degree: 28, en: "A large aviary", ja: null },
    299: { sign: "Capricorn", degree: 29, en: "A woman reading tea leaves", ja: null },
    300: { sign: "Capricorn", degree: 30, en: "Directors of a large firm meet in secret conference", ja: null },
    301: { sign: "Aquarius", degree: 1, en: "An old adobe mission", ja: null },
    302: { sign: "Aquarius", degree: 2, en: "An unexpected thunderstorm", ja: null },
    303: { sign: "Aquarius", degree: 3, en: "A deserter from the navy", ja: null },
    304: { sign: "Aquarius", degree: 4, en: "A Hindu healer", ja: null },
    305: { sign: "Aquarius", degree: 5, en: "A council of ancestors", ja: null },
    306: { sign: "Aquarius", degree: 6, en: "A masked figure performs ritualistic acts in a mystery play", ja: null },
    307: { sign: "Aquarius", degree: 7, en: "A child born out of an eggshell", ja: null },
    308: { sign: "Aquarius", degree: 8, en: "Beautifully gowned wax figures on display", ja: null },
    309: { sign: "Aquarius", degree: 9, en: "A flag is seen turning into an eagle", ja: null },
    310: { sign: "Aquarius", degree: 10, en: "A popularity that proves to be fleeting", ja: null },
    311: { sign: "Aquarius", degree: 11, en: "During a silent hour, a man receives a new inspiration which may change his life", ja: null },
    312: { sign: "Aquarius", degree: 12, en: "People on a vast staircase, graduated upwards", ja: null },
    313: { sign: "Aquarius", degree: 13, en: "A barometer", ja: null },
    314: { sign: "Aquarius", degree: 14, en: "A train entering a tunnel", ja: null },
    315: { sign: "Aquarius", degree: 15, en: "Two lovebirds sitting on a fence and singing happily", ja: null },
    316: { sign: "Aquarius", degree: 16, en: "A big-businessman at his desk", ja: null },
    317: { sign: "Aquarius", degree: 17, en: "A watchdog standing guard, protecting his master and his possessions", ja: null },
    318: { sign: "Aquarius", degree: 18, en: "A man being unmasked at a masquerade", ja: null },
    319: { sign: "Aquarius", degree: 19, en: "A forest fire quenched", ja: null },
    320: { sign: "Aquarius", degree: 20, en: "A large white dove bearing a message", ja: null },
    321: { sign: "Aquarius", degree: 21, en: "A woman disappointed and disillusioned, courageously facing a seemingly empty life", ja: null },
    322: { sign: "Aquarius", degree: 22, en: "A rug placed on a floor for children to play on", ja: null },
    323: { sign: "Aquarius", degree: 23, en: "A big bear sitting down and waving all its paws", ja: null },
    324: { sign: "Aquarius", degree: 24, en: "A man turning his back on his passions teaches deep wisdom from his experience", ja: null },
    325: { sign: "Aquarius", degree: 25, en: "A butterfly with the right wing more perfectly formed", ja: null },
    326: { sign: "Aquarius", degree: 26, en: "A garage man testing a car's battery with a hydrometer", ja: null },
    327: { sign: "Aquarius", degree: 27, en: "An ancient pottery bowl filled with fresh violets", ja: null },
    328: { sign: "Aquarius", degree: 28, en: "A tree felled and sawed to ensure a supply of wood for the winter", ja: null },
    329: { sign: "Aquarius", degree: 29, en: "A butterfly emerging from a chrysalis", ja: null },
    330: { sign: "Aquarius", degree: 30, en: "Moon-lit fields, once Babylon, are blooming white", ja: null },
    331: { sign: "Pisces", degree: 1, en: "A crowded public market place", ja: null },
    332: { sign: "Pisces", degree: 2, en: "A squirrel hiding from hunters", ja: null },
    333: { sign: "Pisces", degree: 3, en: "A petrified forest", ja: null },
    334: { sign: "Pisces", degree: 4, en: "Heavy car traffic on a narrow isthmus linking two seaside resorts", ja: null },
    335: { sign: "Pisces", degree: 5, en: "A church bazaar", ja: null },
    336: { sign: "Pisces", degree: 6, en: "A parade of army officers in full dress", ja: null },
    337: { sign: "Pisces", degree: 7, en: "Illuminated by a shaft of light, a large cross lies on rocks surrounded by sea and mist", ja: null },
    338: { sign: "Pisces", degree: 8, en: "A girl blowing a bugle", ja: null },
    339: { sign: "Pisces", degree: 9, en: "The race begins: intent on outdistancing his rivals, a jockey spurs his horse to great speed", ja: null },
    340: { sign: "Pisces", degree: 10, en: "An aviator in the clouds", ja: null },
    341: { sign: "Pisces", degree: 11, en: "Men travelling a narrow path, seeking illumination", ja: null },
    342: { sign: "Pisces", degree: 12, en: "An examination of initiates in the sanctuary of an occult brotherhood", ja: null },
    343: { sign: "Pisces", degree: 13, en: "A sword, used in many battles, in a museum", ja: null },
    344: { sign: "Pisces", degree: 14, en: "A lady wrapped in fox fur", ja: null },
    345: { sign: "Pisces", degree: 15, en: "An officer drilling his men in a simulated attack", ja: null },
    346: { sign: "Pisces", degree: 16, en: "In a quiet moment, a creative individual experiences the flow of inspiration", ja: null },
    347: { sign: "Pisces", degree: 17, en: "An Easter promenade", ja: null },
    348: { sign: "Pisces", degree: 18, en: "In a huge tent a famous revivalist conducts his meeting with a spectacular performance", ja: null },
    349: { sign: "Pisces", degree: 19, en: "A master instructing his disciple", ja: null },
    350: { sign: "Pisces", degree: 20, en: "A table set for an evening meal", ja: null },
    351: { sign: "Pisces", degree: 21, en: "A little white lamb, a child and a Chinese servant", ja: null },
    352: { sign: "Pisces", degree: 22, en: "A prophet bringing down the new law from Mount Sinai", ja: null },
    353: { sign: "Pisces", degree: 23, en: "A materializing medium giving a seance", ja: null },
    354: { sign: "Pisces", degree: 24, en: "An inhabited island", ja: null },
    355: { sign: "Pisces", degree: 25, en: "The purging of the priesthood", ja: null },
    356: { sign: "Pisces", degree: 26, en: "A new moon reveals that it's time for people to go ahead with their different projects", ja: null },
    357: { sign: "Pisces", degree: 27, en: "A harvest moon illuminates the sky", ja: null },
    358: { sign: "Pisces", degree: 28, en: "A fertile garden under the full moon", ja: null },
    359: { sign: "Pisces", degree: 29, en: "Light breaking into many colors as it passes through a prism", ja: null },
    360: { sign: "Pisces", degree: 30, en: "A majestic rock formation, like a face, is idealized by a boy who takes it as his ideal of greatness, and as he grows up, begins to look like it", ja: null },
  };
});
