/*
 * sabian.js — サビアンシンボル360度データ
 * data/sabian_symbols_en.json から生成。ja が null の間は英語を表示。
 * ja欄はみっちゃんが自分のメモで埋めていくスロット（data/sabian_symbols_ja_notes.json 経由で再生成可）。
 * キー: 絶対度数 1..360（牡羊座1度=1）。degree = サイン内サビアン度数（1..30）。
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) { module.exports = factory(); }
  else { root.SABIAN = factory(); }
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";
  return {
    1: { sign: "Aries", degree: 1, en: "A Woman Just Risen from the Sea, a Seal Is Embracing Her", ja: null },
    2: { sign: "Aries", degree: 2, en: "A Comedian Entertaining a Group", ja: null },
    3: { sign: "Aries", degree: 3, en: "A Cameo Profile of a Man in the Outline of His Country", ja: null },
    4: { sign: "Aries", degree: 4, en: "Two Lovers Strolling Through a Garden Wall", ja: null },
    5: { sign: "Aries", degree: 5, en: "A Triangle with Wings", ja: null },
    6: { sign: "Aries", degree: 6, en: "A Square, One Side More Strongly Marked", ja: null },
    7: { sign: "Aries", degree: 7, en: "A Man Successfully Expressing Himself in Two Realms at Once", ja: null },
    8: { sign: "Aries", degree: 8, en: "A Large Woman's Hat with Streamers Blown by the East Wind", ja: null },
    9: { sign: "Aries", degree: 9, en: "A Crystal Gazer", ja: null },
    10: { sign: "Aries", degree: 10, en: "A Teacher Gives New Symbolic Forms to Traditional Images", ja: null },
    11: { sign: "Aries", degree: 11, en: "An Old Adobe Mission", ja: null },
    12: { sign: "Aries", degree: 12, en: "A Flock of Wild Geese Flying in Formation", ja: null },
    13: { sign: "Aries", degree: 13, en: "A Bomb Which Failed to Explode Is Now Safely Buried", ja: null },
    14: { sign: "Aries", degree: 14, en: "A Serpent Coiling Near a Man and a Woman", ja: null },
    15: { sign: "Aries", degree: 15, en: "An Ancient Bas-Relief Carved in Granite Survives in a Jungle", ja: null },
    16: { sign: "Aries", degree: 16, en: "Brownies Dancing in the Setting Sun", ja: null },
    17: { sign: "Aries", degree: 17, en: "Two Prim Spinsters Sit in Silent Companionship", ja: null },
    18: { sign: "Aries", degree: 18, en: "An Empty Hammock", ja: null },
    19: { sign: "Aries", degree: 19, en: "A Young Girl Feeding Birds in Winter", ja: null },
    20: { sign: "Aries", degree: 20, en: "A Young Woman Awaiting a Sailboat", ja: null },
    21: { sign: "Aries", degree: 21, en: "A Pugilist Enters the Ring", ja: null },
    22: { sign: "Aries", degree: 22, en: "A Man Duly Provided with Power to Meet His Great Toil", ja: null },
    23: { sign: "Aries", degree: 23, en: "A Young Man Awakens to New Life and Duty", ja: null },
    24: { sign: "Aries", degree: 24, en: "A Rug Placed on a Floor for Children to Play On", ja: null },
    25: { sign: "Aries", degree: 25, en: "A Double Promise Reveals Its Inner and Outer Meanings", ja: null },
    26: { sign: "Aries", degree: 26, en: "A Man Possessed of More Gifts than He Can Hold", ja: null },
    27: { sign: "Aries", degree: 27, en: "A Merry-Go-Round", ja: null },
    28: { sign: "Aries", degree: 28, en: "A Large Disappointed Audience", ja: null },
    29: { sign: "Aries", degree: 29, en: "The Gate to the Garden of All Fulfilled Desires", ja: null },
    30: { sign: "Aries", degree: 30, en: "A Duck Pond and Its Brood", ja: null },
    31: { sign: "Taurus", degree: 1, en: "A Clear Mountain Stream", ja: null },
    32: { sign: "Taurus", degree: 2, en: "An Electrical Storm", ja: null },
    33: { sign: "Taurus", degree: 3, en: "Steps Up to a Lawn Blooming with Clover", ja: null },
    34: { sign: "Taurus", degree: 4, en: "Wind Clouds and Flying Birds", ja: null },
    35: { sign: "Taurus", degree: 5, en: "A Widow at an Open Grave", ja: null },
    36: { sign: "Taurus", degree: 6, en: "A Woodchuck Looking for Its Burrow", ja: null },
    37: { sign: "Taurus", degree: 7, en: "An Old Indian Woman Selling Beads", ja: null },
    38: { sign: "Taurus", degree: 8, en: "A Sleigh Without Snow", ja: null },
    39: { sign: "Taurus", degree: 9, en: "A Fully Decorated Christmas Tree", ja: null },
    40: { sign: "Taurus", degree: 10, en: "A Red Cross Nurse", ja: null },
    41: { sign: "Taurus", degree: 11, en: "A Woman Sprinkling Flowers", ja: null },
    42: { sign: "Taurus", degree: 12, en: "A Young Couple Walk Down the Main Street of Their Town, Just Married", ja: null },
    43: { sign: "Taurus", degree: 13, en: "A Porter Carrying Heavy Baggage", ja: null },
    44: { sign: "Taurus", degree: 14, en: "A Sunday Crowd Enjoying the Beach", ja: null },
    45: { sign: "Taurus", degree: 15, en: "A Man with a Machete Cuts His Way Through Dense Jungle", ja: null },
    46: { sign: "Taurus", degree: 16, en: "An Old Man Attempting to Reveal the Ultimate Mysteries of Life", ja: null },
    47: { sign: "Taurus", degree: 17, en: "An Indian Chief Claims Power from the Assembled Braves", ja: null },
    48: { sign: "Taurus", degree: 18, en: "A Woman Airing an Old Bag Through a Sunny Window", ja: null },
    49: { sign: "Taurus", degree: 19, en: "A New Continent Rising Out of the Ocean", ja: null },
    50: { sign: "Taurus", degree: 20, en: "A Woman, in Pastel Colors, Carrying a Heavy and Valuable but Veiled Load", ja: null },
    51: { sign: "Taurus", degree: 21, en: "White Dove Flying Over Troubled Waters", ja: null },
    52: { sign: "Taurus", degree: 22, en: "A Jewelry Shop Filled with the Most Magnificent Jewels", ja: null },
    53: { sign: "Taurus", degree: 23, en: "Vibrant Aurora Borealis Light Up a Night Sky", ja: null },
    54: { sign: "Taurus", degree: 24, en: "A Bull Fight", ja: null },
    55: { sign: "Taurus", degree: 25, en: "A Vast Public Park", ja: null },
    56: { sign: "Taurus", degree: 26, en: "A Squaw Selling Beads", ja: null },
    57: { sign: "Taurus", degree: 27, en: "A Peacock Parading on the Terrace of an Old Castle", ja: null },
    58: { sign: "Taurus", degree: 28, en: "A Woman, Assisted by a Sailor, Adds Coal to a Ship's Furnace", ja: null },
    59: { sign: "Taurus", degree: 29, en: "Two Cobblers Working at a Table", ja: null },
    60: { sign: "Taurus", degree: 30, en: "A Peacock Displays His Magnificent Tail", ja: null },
    61: { sign: "Gemini", degree: 1, en: "A Glass-Bottomed Boat Reveals Under-Sea Wonders", ja: null },
    62: { sign: "Gemini", degree: 2, en: "Santa Claus Furtively Filling Stockings Hung by a Fireplace", ja: null },
    63: { sign: "Gemini", degree: 3, en: "The Garden of the Tuileries in Paris", ja: null },
    64: { sign: "Gemini", degree: 4, en: "Holly and Mistletoe Bring Christmas Spirit into a Home", ja: null },
    65: { sign: "Gemini", degree: 5, en: "A Radical Magazine Asking for Action", ja: null },
    66: { sign: "Gemini", degree: 6, en: "A Man with a Rakish Silk Hat Muffled Against the Cold", ja: null },
    67: { sign: "Gemini", degree: 7, en: "A Council of Ancestors", ja: null },
    68: { sign: "Gemini", degree: 8, en: "Aeroplane Performing a Nose Dive", ja: null },
    69: { sign: "Gemini", degree: 9, en: "A Quiver Filled with Arrows", ja: null },
    70: { sign: "Gemini", degree: 10, en: "Aroused Strikers Round a Factory", ja: null },
    71: { sign: "Gemini", degree: 11, en: "A Woman Activist in an Emotional Speech Dramatizing Her Cause", ja: null },
    72: { sign: "Gemini", degree: 12, en: "A Topless Woman Carries a Kettle", ja: null },
    73: { sign: "Gemini", degree: 13, en: "A Middle-Aged Woman, Her Long Hair Flowing Over Her Shoulders", ja: null },
    74: { sign: "Gemini", degree: 14, en: "Two People, Living Far Apart, in Telepathic Communication", ja: null },
    75: { sign: "Gemini", degree: 15, en: "Two Dutch Children Talking, Exchanging Their Knowledge of Shells", ja: null },
    76: { sign: "Gemini", degree: 16, en: "A Man on a Magic Carpet Observing Vast Vistas Below Him", ja: null },
    77: { sign: "Gemini", degree: 17, en: "A Bat Flying in the Twilight", ja: null },
    78: { sign: "Gemini", degree: 18, en: "Deep-Sea Divers", ja: null },
    79: { sign: "Gemini", degree: 19, en: "Snowflakes Under a Microscope", ja: null },
    80: { sign: "Gemini", degree: 20, en: "A Just Man Enjoying Himself in Nature", ja: null },
    81: { sign: "Gemini", degree: 21, en: "A Cafeteria", ja: null },
    82: { sign: "Gemini", degree: 22, en: "A Woman Reading Tea Leaves", ja: null },
    83: { sign: "Gemini", degree: 23, en: "Three Fledglings in a Nest High in a Tree", ja: null },
    84: { sign: "Gemini", degree: 24, en: "A Man Studying a Mandala in Front of Him, with the Help of a Book", ja: null },
    85: { sign: "Gemini", degree: 25, en: "Winter Frost in the Woods", ja: null },
    86: { sign: "Gemini", degree: 26, en: "A Man on a Magic Carpet Observing Vast Vistas Below Him", ja: null },
    87: { sign: "Gemini", degree: 27, en: "A Young Woman, Her Bobbed Hair Fashionably Waved", ja: null },
    88: { sign: "Gemini", degree: 28, en: "A Man Alert to Warnings from Dreams", ja: null },
    89: { sign: "Gemini", degree: 29, en: "The First Mockingbird of Spring Sings from a Tree Top", ja: null },
    90: { sign: "Gemini", degree: 30, en: "A Parade of Bathing Beauties Before Large Beach Crowds", ja: null },
    91: { sign: "Cancer", degree: 1, en: "A Man and a Woman Have Just Emerged from the Sea in a New-Born State", ja: null },
    92: { sign: "Cancer", degree: 2, en: "A Man on a Rock Watches the Waves", ja: null },
    93: { sign: "Cancer", degree: 3, en: "An Arctic Explorer Leads a Dog Sled", ja: null },
    94: { sign: "Cancer", degree: 4, en: "A Cat Arguing with a Mouse", ja: null },
    95: { sign: "Cancer", degree: 5, en: "At a Railroad Crossing, an Automobile Is Wrecked by a Train", ja: null },
    96: { sign: "Cancer", degree: 6, en: "A Man Watching His Ideals Taking a Concrete Form Before His Inner Vision", ja: null },
    97: { sign: "Cancer", degree: 7, en: "A Man Sitting for a Portrait", ja: null },
    98: { sign: "Cancer", degree: 8, en: "A Woman and Two Men Castaways on a Small Island of the South Seas", ja: null },
    99: { sign: "Cancer", degree: 9, en: "A Small, Naked Girl Bends Over a Pond Trying to Catch a Fish", ja: null },
    100: { sign: "Cancer", degree: 10, en: "A Fleet of Airplanes Flying Over the Ocean", ja: null },
    101: { sign: "Cancer", degree: 11, en: "A Clown Caricatures Well-Known Personalities", ja: null },
    102: { sign: "Cancer", degree: 12, en: "A Woman Bites into an Apple, an Uncertain Look Registers in Her Face", ja: null },
    103: { sign: "Cancer", degree: 13, en: "A Family Tree", ja: null },
    104: { sign: "Cancer", degree: 14, en: "A Very Old Man Facing a Vast Dark Space to the Northeast", ja: null },
    105: { sign: "Cancer", degree: 15, en: "A Group of People Who Have Overeaten and Enjoyed It", ja: null },
    106: { sign: "Cancer", degree: 16, en: "A Man Studying a Chart to Discover the Location of Hidden Treasure", ja: null },
    107: { sign: "Cancer", degree: 17, en: "The Meeting of a Literary Society", ja: null },
    108: { sign: "Cancer", degree: 18, en: "A Hen Scratching for Her Chicks", ja: null },
    109: { sign: "Cancer", degree: 19, en: "A Priest Performing a Marriage Ceremony", ja: null },
    110: { sign: "Cancer", degree: 20, en: "A Hen Slightly Ill Watches Her Chicks", ja: null },
    111: { sign: "Cancer", degree: 21, en: "A Prima Donna Singing", ja: null },
    112: { sign: "Cancer", degree: 22, en: "A Young Woman Awaiting a Sailboat's Return with Fear in Her Heart", ja: null },
    113: { sign: "Cancer", degree: 23, en: "A Man Bringing Down Baskets Full of Grapes from a Hillside Vineyard", ja: null },
    114: { sign: "Cancer", degree: 24, en: "A Woman and Two Men on a Bit of Sunlit Land Facing South", ja: null },
    115: { sign: "Cancer", degree: 25, en: "A Greek Muse Weighing Twins in Her Golden Scales", ja: null },
    116: { sign: "Cancer", degree: 26, en: "Guests Are Reading in the Library of a Luxurious Home", ja: null },
    117: { sign: "Cancer", degree: 27, en: "A Storm in a Canyon", ja: null },
    118: { sign: "Cancer", degree: 28, en: "A Modern Ark for Safety in a Time of Floods", ja: null },
    119: { sign: "Cancer", degree: 29, en: "A Movie Star Modelling for the Public", ja: null },
    120: { sign: "Cancer", degree: 30, en: "A Daughter of the American Revolution", ja: null },
    121: { sign: "Leo", degree: 1, en: "A Man Having Risen from the Sea, a Seagull Flies Over Him and Screeches", ja: null },
    122: { sign: "Leo", degree: 2, en: "An Epidemic of Mumps", ja: null },
    123: { sign: "Leo", degree: 3, en: "A Squirrel Hiding from Hunters", ja: null },
    124: { sign: "Leo", degree: 4, en: "A Man Formally Dressed Stands Near Trophies He Brought Back from a Hunting Expedition", ja: null },
    125: { sign: "Leo", degree: 5, en: "A Group of Little Children, Facing the Sun, Play Games in a Circle", ja: null },
    126: { sign: "Leo", degree: 6, en: "An Old Fashioned Well", ja: null },
    127: { sign: "Leo", degree: 7, en: "The Constellations of Stars in the Sky", ja: null },
    128: { sign: "Leo", degree: 8, en: "A Large Camel Crossing a Vast and Forbidding Desert", ja: null },
    129: { sign: "Leo", degree: 9, en: "A Communist Activist Spreading His Revolutionary Ideals", ja: null },
    130: { sign: "Leo", degree: 10, en: "A Girl Blowing a Bugle", ja: null },
    131: { sign: "Leo", degree: 11, en: "Cubist Art Reveals Hidden Angles", ja: null },
    132: { sign: "Leo", degree: 12, en: "An Evening Lawn Party of Adults", ja: null },
    133: { sign: "Leo", degree: 13, en: "An Old Sea Captain Rocking Himself on the Porch of His Cottage", ja: null },
    134: { sign: "Leo", degree: 14, en: "A Bald-Headed Man Who Has Seized Power", ja: null },
    135: { sign: "Leo", degree: 15, en: "A Storm at Sea", ja: null },
    136: { sign: "Leo", degree: 16, en: "An Unexpected Thunderstorm", ja: null },
    137: { sign: "Leo", degree: 17, en: "A Volunteer Church Choir Singing Religious Hymns", ja: null },
    138: { sign: "Leo", degree: 18, en: "A Chemist Conducts an Experiment for His Students", ja: null },
    139: { sign: "Leo", degree: 19, en: "A Houseboat Party", ja: null },
    140: { sign: "Leo", degree: 20, en: "Blood Rushes to a Man's Head as His Vital Energies Are Mobilized", ja: null },
    141: { sign: "Leo", degree: 21, en: "The Constellation of Stars in the Sky, Formed to Resemble a Fixed Symbolic Design", ja: null },
    142: { sign: "Leo", degree: 22, en: "A Rainbow Lyrically Concludes a Great Storm", ja: null },
    143: { sign: "Leo", degree: 23, en: "A Bareback Rider Astonishes the Crowd", ja: null },
    144: { sign: "Leo", degree: 24, en: "An Untidy, Unkempt Man", ja: null },
    145: { sign: "Leo", degree: 25, en: "A Flag Turns into an Eagle That Crows", ja: null },
    146: { sign: "Leo", degree: 26, en: "An Old Fashioned Woman and a Very Modern Girl Talk Together", ja: null },
    147: { sign: "Leo", degree: 27, en: "Daybreak — the Luminescence of Dawn in the Eastern Sky", ja: null },
    148: { sign: "Leo", degree: 28, en: "A Fat Boy Mowing the Lawn", ja: null },
    149: { sign: "Leo", degree: 29, en: "A Mermaid Emerges from the Ocean, Ready for Rebirth in Human Form", ja: null },
    150: { sign: "Leo", degree: 30, en: "A Fire Worshipper", ja: null },
    151: { sign: "Virgo", degree: 1, en: "In a Portrait, the Significant Features of a Man's Head Are Artistically Emphasized", ja: null },
    152: { sign: "Virgo", degree: 2, en: "A Fine Lace Handkerchief, Old and Yellowed", ja: null },
    153: { sign: "Virgo", degree: 3, en: "Two Guardian Angels Bringing Protection", ja: null },
    154: { sign: "Virgo", degree: 4, en: "Wisps of Cloud, Like Wings, Are Streaming from a Reef", ja: null },
    155: { sign: "Virgo", degree: 5, en: "A Man Becoming Aware of Nature Spirits and Normally Unseen Beings", ja: null },
    156: { sign: "Virgo", degree: 6, en: "A Merry-Go-Round", ja: null },
    157: { sign: "Virgo", degree: 7, en: "A Harem", ja: null },
    158: { sign: "Virgo", degree: 8, en: "A Ouija Board", ja: null },
    159: { sign: "Virgo", degree: 9, en: "A Man Gaining Secret Knowledge from an Ancient Scroll He Is Reading", ja: null },
    160: { sign: "Virgo", degree: 10, en: "Two Heads Looking Out and Beyond the Shadows", ja: null },
    161: { sign: "Virgo", degree: 11, en: "A Boy Molded in His Mother's Aspirations for Him", ja: null },
    162: { sign: "Virgo", degree: 12, en: "A Fluttering, Torn Flag on a Battle-Scarred Trench Beachhead", ja: null },
    163: { sign: "Virgo", degree: 13, en: "A Bride with Her Veil Snatched by the Wind", ja: null },
    164: { sign: "Virgo", degree: 14, en: "A Family Having Fun on Its Own Backyard Lawn", ja: null },
    165: { sign: "Virgo", degree: 15, en: "A Fine Lace Handkerchief, Old and Yellowed with Time", ja: null },
    166: { sign: "Virgo", degree: 16, en: "A Man Watches His Ideals Taking a Concrete Form", ja: null },
    167: { sign: "Virgo", degree: 17, en: "A Volcanic Eruption", ja: null },
    168: { sign: "Virgo", degree: 18, en: "A Swimming Race", ja: null },
    169: { sign: "Virgo", degree: 19, en: "A Farm Boy Milking a Cow", ja: null },
    170: { sign: "Virgo", degree: 20, en: "A Rushing Torrent Speeding Between Rocky Chasms", ja: null },
    171: { sign: "Virgo", degree: 21, en: "A Girl's Basketball Team", ja: null },
    172: { sign: "Virgo", degree: 22, en: "A Child Giving Birds a Drink at a Fountain", ja: null },
    173: { sign: "Virgo", degree: 23, en: "An Animal Trainer", ja: null },
    174: { sign: "Virgo", degree: 24, en: "Angels Chanting Devotional Songs", ja: null },
    175: { sign: "Virgo", degree: 25, en: "Miners Are Emerging from a Deep Coal Mine", ja: null },
    176: { sign: "Virgo", degree: 26, en: "A Merman Emerges from the Ocean, He Is About to Try Life on Land", ja: null },
    177: { sign: "Virgo", degree: 27, en: "Through Imagination, a Lost Balloon Becomes a New World", ja: null },
    178: { sign: "Virgo", degree: 28, en: "A Bald-Headed Man Who Has Seized Political Power", ja: null },
    179: { sign: "Virgo", degree: 29, en: "A Man Gathering Together the Threads of His Career", ja: null },
    180: { sign: "Virgo", degree: 30, en: "A Fruitful Season Brings a Great Harvest", ja: null },
    181: { sign: "Libra", degree: 1, en: "A Butterfly Preserved and Made Perfect with a Dart Through It", ja: null },
    182: { sign: "Libra", degree: 2, en: "The Light of the Sixth Race Transmuted to the Seventh", ja: null },
    183: { sign: "Libra", degree: 3, en: "The Dawn of a New Day Reveals Everything Changed", ja: null },
    184: { sign: "Libra", degree: 4, en: "A Group of Young People Sit in Spiritual Communion Around a Campfire", ja: null },
    185: { sign: "Libra", degree: 5, en: "A Man Watches His Ideals Taking Concrete Form Before His Inner Vision", ja: null },
    186: { sign: "Libra", degree: 6, en: "A Man's Head, Regenerated, from Which a Star Blazes Forth", ja: null },
    187: { sign: "Libra", degree: 7, en: "A Chubby Boy on a Hobby Horse", ja: null },
    188: { sign: "Libra", degree: 8, en: "A Blazing Fireplace in a Deserted Home", ja: null },
    189: { sign: "Libra", degree: 9, en: "Three Old Masters Hanging in a Special Room in an Art Gallery", ja: null },
    190: { sign: "Libra", degree: 10, en: "A Canoe Approaching Safety Through Dangerous Waters", ja: null },
    191: { sign: "Libra", degree: 11, en: "A Professor Peering Over His Glasses at His Students", ja: null },
    192: { sign: "Libra", degree: 12, en: "Miners Emerging from a Deep Coal Mine", ja: null },
    193: { sign: "Libra", degree: 13, en: "Children Blowing Soap Bubbles", ja: null },
    194: { sign: "Libra", degree: 14, en: "In the Heat of the Noon, a Man Takes a Siesta", ja: null },
    195: { sign: "Libra", degree: 15, en: "Circular Paths", ja: null },
    196: { sign: "Libra", degree: 16, en: "In a Collection of Perfect Objects, a Few Are Not Genuine", ja: null },
    197: { sign: "Libra", degree: 17, en: "A Retired Sea Captain Watches Ships Entering and Leaving the Harbor", ja: null },
    198: { sign: "Libra", degree: 18, en: "Two Men Placed Under Arrest", ja: null },
    199: { sign: "Libra", degree: 19, en: "A Gang of Robbers in Hiding", ja: null },
    200: { sign: "Libra", degree: 20, en: "A Jewish Rabbi Performing His Duties", ja: null },
    201: { sign: "Libra", degree: 21, en: "A Little Boy Carrying a Bird Cage Brings the First Spring Voices to His Mother", ja: null },
    202: { sign: "Libra", degree: 22, en: "A Child Is Born Out of an Eggshell", ja: null },
    203: { sign: "Libra", degree: 23, en: "A Third Wing on the Left Side of a Butterfly Gives It the Full Assurance of a Complete Metamorphosis", ja: null },
    204: { sign: "Libra", degree: 24, en: "A Woman Rising Out of Water, a Seal Rising and Applauding", ja: null },
    205: { sign: "Libra", degree: 25, en: "An Ouija Board", ja: null },
    206: { sign: "Libra", degree: 26, en: "Illumined by a Ray of Light, a Large Cross Lies on Rocks Surrounded by the Sea", ja: null },
    207: { sign: "Libra", degree: 27, en: "An Airplane Sails, Serene and Steady, Through a Clear Sky", ja: null },
    208: { sign: "Libra", degree: 28, en: "A Man in Deep Gloom, Unnoticed, Angels Come to His Aid", ja: null },
    209: { sign: "Libra", degree: 29, en: "Mankind's Vast Enduring Effort to Reach for Knowledge Transferable from Generation to Generation", ja: null },
    210: { sign: "Libra", degree: 30, en: "A Duck Pond and Its Brood, Late in the Season", ja: null },
    211: { sign: "Scorpio", degree: 1, en: "A Deep Sea Diver", ja: null },
    212: { sign: "Scorpio", degree: 2, en: "A Broken Bottle and Spilled Perfume", ja: null },
    213: { sign: "Scorpio", degree: 3, en: "Youths Watching a Bright Fire Reflected in a River", ja: null },
    214: { sign: "Scorpio", degree: 4, en: "A Massive, Rocky Shore Resists the Pounding of the Sea", ja: null },
    215: { sign: "Scorpio", degree: 5, en: "A Sight-Seeing Bus Filled with Tourists", ja: null },
    216: { sign: "Scorpio", degree: 6, en: "A Gold Rush Tears Men Away from Their Native Soil", ja: null },
    217: { sign: "Scorpio", degree: 7, en: "Deep-Sea Divers", ja: null },
    218: { sign: "Scorpio", degree: 8, en: "A Massive Stone Table Fills a Cave", ja: null },
    219: { sign: "Scorpio", degree: 9, en: "A Dentist at Work", ja: null },
    220: { sign: "Scorpio", degree: 10, en: "A Fellowship Supper Reunites Old Comrades After Years of Separation", ja: null },
    221: { sign: "Scorpio", degree: 11, en: "A Drowning Man Is Being Rescued", ja: null },
    222: { sign: "Scorpio", degree: 12, en: "An Official Embassy Ball", ja: null },
    223: { sign: "Scorpio", degree: 13, en: "Children Playing Together on a Wide Lawn", ja: null },
    224: { sign: "Scorpio", degree: 14, en: "Telephone Linemen at Work Installing New Connections", ja: null },
    225: { sign: "Scorpio", degree: 15, en: "Children Blowing Soap Bubbles", ja: null },
    226: { sign: "Scorpio", degree: 16, en: "A Girl's Face Breaking into a Smile", ja: null },
    227: { sign: "Scorpio", degree: 17, en: "A Woman, Filled with Anguish, Kneeling in Prayer", ja: null },
    228: { sign: "Scorpio", degree: 18, en: "A Woman Draws Two Faces on a Scroll, One of Herself, One of the Public Self", ja: null },
    229: { sign: "Scorpio", degree: 19, en: "A Parrot Listening and then Talking, Repeats a Conversation He Has Overheard", ja: null },
    230: { sign: "Scorpio", degree: 20, en: "A Woman Drawing Two Amazed Faces on a Scroll", ja: null },
    231: { sign: "Scorpio", degree: 21, en: "Obeying His Conscience, a Soldier Resists War", ja: null },
    232: { sign: "Scorpio", degree: 22, en: "A Woman in Pastel Colors Carrying a Heavy and Valuable but Veiled Load", ja: null },
    233: { sign: "Scorpio", degree: 23, en: "Refugees Seeking Shelter Crossing a Dangerous, Cold Winter Field", ja: null },
    234: { sign: "Scorpio", degree: 24, en: "Crowds Coming Down with Sun-Helmets in an Oriental City", ja: null },
    235: { sign: "Scorpio", degree: 25, en: "Slave Girls Bring Costly Presents to Their Ruler", ja: null },
    236: { sign: "Scorpio", degree: 26, en: "A Woman, Her Long Hair Bobbed, Sits in Front of a Mirror", ja: null },
    237: { sign: "Scorpio", degree: 27, en: "A Peacock Parades in Full Regalia on an Ancient Estate", ja: null },
    238: { sign: "Scorpio", degree: 28, en: "The King of the Fairies Approaching His Domain", ja: null },
    239: { sign: "Scorpio", degree: 29, en: "Great Wild Geese Flying Through a Storm", ja: null },
    240: { sign: "Scorpio", degree: 30, en: "Children Are Playing on the Shore of a Pond That Suggests the Ocean", ja: null },
    241: { sign: "Sagittarius", degree: 1, en: "A Native Legend Symbolized in a Totem Pole Near a Sea Coast Village Uses Animal Forms to Depict the Spirit of the Tribe", ja: null },
    242: { sign: "Sagittarius", degree: 2, en: "The Ground Hog Looking for Its Shadow on Ground Hog Day", ja: null },
    243: { sign: "Sagittarius", degree: 3, en: "Two Men Playing Chess", ja: null },
    244: { sign: "Sagittarius", degree: 4, en: "A Little Child Learning to Walk", ja: null },
    245: { sign: "Sagittarius", degree: 5, en: "An Old Owl High Up in a Tree", ja: null },
    246: { sign: "Sagittarius", degree: 6, en: "A Game of Cricket", ja: null },
    247: { sign: "Sagittarius", degree: 7, en: "Cupid Knocks at the Door of a Human Heart", ja: null },
    248: { sign: "Sagittarius", degree: 8, en: "A Petrified Forest", ja: null },
    249: { sign: "Sagittarius", degree: 9, en: "A Mother Leads Her Small Child Step by Step Up a Steep Stairway", ja: null },
    250: { sign: "Sagittarius", degree: 10, en: "The Pope Blessing the Faithful", ja: null },
    251: { sign: "Sagittarius", degree: 11, en: "A Golden-Haired Goddess of Opportunity", ja: null },
    252: { sign: "Sagittarius", degree: 12, en: "A Flag Bearer in a Battle", ja: null },
    253: { sign: "Sagittarius", degree: 13, en: "A Widowed Woman, Past Her Prime, Meets a Group of Women Representing Public Opinion", ja: null },
    254: { sign: "Sagittarius", degree: 14, en: "Pheasants Display Their Brilliant Colors on a Private Estate", ja: null },
    255: { sign: "Sagittarius", degree: 15, en: "The Ground Hog Looking for its Shadow", ja: null },
    256: { sign: "Sagittarius", degree: 16, en: "A Kindergarten Class Is Playing in a Backyard", ja: null },
    257: { sign: "Sagittarius", degree: 17, en: "An Easter Sunrise Service", ja: null },
    258: { sign: "Sagittarius", degree: 18, en: "A Fat Boy Mowing the Lawn", ja: null },
    259: { sign: "Sagittarius", degree: 19, en: "Snowflakes Under the Microscope", ja: null },
    260: { sign: "Sagittarius", degree: 20, en: "A Chubby Boy on a Hobby Horse", ja: null },
    261: { sign: "Sagittarius", degree: 21, en: "A Child and a Dog, Wearing Borrowed Adult Clothing, Try to Reproduce a Church Ceremony", ja: null },
    262: { sign: "Sagittarius", degree: 22, en: "A Bluebird Standing at the Door of the House", ja: null },
    263: { sign: "Sagittarius", degree: 23, en: "A Woman Reading Tea Leaves", ja: null },
    264: { sign: "Sagittarius", degree: 24, en: "A Bridge Being Built Across a Gorge", ja: null },
    265: { sign: "Sagittarius", degree: 25, en: "Indians Making Camp in New Territory", ja: null },
    266: { sign: "Sagittarius", degree: 26, en: "A Sculptor Awakens the Spirit Sleeping in the Stone", ja: null },
    267: { sign: "Sagittarius", degree: 27, en: "The Music of the Spheres", ja: null },
    268: { sign: "Sagittarius", degree: 28, en: "A Fat Man Reducing to Regain His Normal Weight", ja: null },
    269: { sign: "Sagittarius", degree: 29, en: "The Pyramids and the Sphinx", ja: null },
    270: { sign: "Sagittarius", degree: 30, en: "A Grandfather Silently Gives Wise Counsel to His Grandchild", ja: null },
    271: { sign: "Capricorn", degree: 1, en: "An Indian Chief Claims Power from the Assembled Braves", ja: null },
    272: { sign: "Capricorn", degree: 2, en: "Pheasants Display Their Brilliant Colors on a Private Estate", ja: null },
    273: { sign: "Capricorn", degree: 3, en: "A Girl's Basketball Team", ja: null },
    274: { sign: "Capricorn", degree: 4, en: "A Human Soul in Its Eagerness for New Experience Descending into the Depths of Matter, Losing All Consciousness of the Light Within", ja: null },
    275: { sign: "Capricorn", degree: 5, en: "An Old Owl Sits Alone on the Branch of a Large Tree", ja: null },
    276: { sign: "Capricorn", degree: 6, en: "A Mountain Pilgrimage", ja: null },
    277: { sign: "Capricorn", degree: 7, en: "A Veiled Prophet Speaks, Seized with the Power of Words He Cannot Retain", ja: null },
    278: { sign: "Capricorn", degree: 8, en: "Birds in the House Singing Happily", ja: null },
    279: { sign: "Capricorn", degree: 9, en: "A Woman Reading Tea Leaves", ja: null },
    280: { sign: "Capricorn", degree: 10, en: "A Militant Peace Advocate in an Argument with an Extremely Militant Officer", ja: null },
    281: { sign: "Capricorn", degree: 11, en: "Pelicans, Disturbed by the Passing of a Boat, Fly away from Their Marshy Home", ja: null },
    282: { sign: "Capricorn", degree: 12, en: "A Student of Nature Lecturing, Revealing Little Known Aspects of Life", ja: null },
    283: { sign: "Capricorn", degree: 13, en: "A Fire Worshiper Meditates on the Ultimate Reality of Existence", ja: null },
    284: { sign: "Capricorn", degree: 14, en: "An Ancient Bas-Relief Carved in Granite Remains a Witness to a Long-Forgotten Culture", ja: null },
    285: { sign: "Capricorn", degree: 15, en: "A Group of People Who Have Overeaten and Enjoyed It, Congratulate the Cook", ja: null },
    286: { sign: "Capricorn", degree: 16, en: "A Repressed Woman Finds a Psychological Release in Nudism", ja: null },
    287: { sign: "Capricorn", degree: 17, en: "A Girl Surreptitiously Bathing in the Nude", ja: null },
    288: { sign: "Capricorn", degree: 18, en: "The Union Jack Flies from a British Warship", ja: null },
    289: { sign: "Capricorn", degree: 19, en: "A Old Bridge Over a Beautiful Stream Is Still Used", ja: null },
    290: { sign: "Capricorn", degree: 20, en: "A Hidden Choir Singing During a Religious Service", ja: null },
    291: { sign: "Capricorn", degree: 21, en: "A Relay Race", ja: null },
    292: { sign: "Capricorn", degree: 22, en: "A Relay Race, a Baton Passed from Runner to Runner", ja: null },
    293: { sign: "Capricorn", degree: 23, en: "A Girl's Basketball Team Winning the Game", ja: null },
    294: { sign: "Capricorn", degree: 24, en: "A Woman, Once the Village Seamstress, Enjoys a Ripe Old Age", ja: null },
    295: { sign: "Capricorn", degree: 25, en: "Many Mice Have Found Shelter in a Boarding House Full of Old Furniture", ja: null },
    296: { sign: "Capricorn", degree: 26, en: "A Woman Suffragist Haranguing the Crowd", ja: null },
    297: { sign: "Capricorn", degree: 27, en: "A Large Group of Pigeons Scattered Suddenly into Flight", ja: null },
    298: { sign: "Capricorn", degree: 28, en: "A Girl's Basketball Team", ja: null },
    299: { sign: "Capricorn", degree: 29, en: "A Large Diamond in the First Stages of the Cutting Process", ja: null },
    300: { sign: "Capricorn", degree: 30, en: "A Woman Reading Tea Leaves While Awaiting a Message", ja: null },
    301: { sign: "Aquarius", degree: 1, en: "An Old Adobe Mission", ja: null },
    302: { sign: "Aquarius", degree: 2, en: "A Sculptor at His Work", ja: null },
    303: { sign: "Aquarius", degree: 3, en: "A Man Turning His Back on His Emotions, He Studies Alone", ja: null },
    304: { sign: "Aquarius", degree: 4, en: "A Man Aspiring to Reach a Higher Type of Existence Cuts Loose from His Anchorage", ja: null },
    305: { sign: "Aquarius", degree: 5, en: "A Butterfly with the Right Wing More Perfectly Formed", ja: null },
    306: { sign: "Aquarius", degree: 6, en: "A Deserter from the Navy", ja: null },
    307: { sign: "Aquarius", degree: 7, en: "A Man Being Unmasked at a Masquerade", ja: null },
    308: { sign: "Aquarius", degree: 8, en: "A Big Bear Sitting Down and Waving All Its Paws", ja: null },
    309: { sign: "Aquarius", degree: 9, en: "A Flag That Turns into an Eagle That Crows", ja: null },
    310: { sign: "Aquarius", degree: 10, en: "A Popularity That Proves to Be Fleeting", ja: null },
    311: { sign: "Aquarius", degree: 11, en: "During a Silent Hour, a Man Receives a New Inspiration Which May Change His Life", ja: null },
    312: { sign: "Aquarius", degree: 12, en: "People on a Vast Staircase, Graduated Upward", ja: null },
    313: { sign: "Aquarius", degree: 13, en: "A Barometer", ja: null },
    314: { sign: "Aquarius", degree: 14, en: "A Train Entering a Tunnel", ja: null },
    315: { sign: "Aquarius", degree: 15, en: "A Massive, Rocky Shore Resists the Pounding of the Sea", ja: null },
    316: { sign: "Aquarius", degree: 16, en: "A Big Bear Sitting Down and Waving All Its Paws", ja: null },
    317: { sign: "Aquarius", degree: 17, en: "A Watchdog Stands Guard, Protecting His Master and His Property", ja: null },
    318: { sign: "Aquarius", degree: 18, en: "A Man Unmasked by Circumstance", ja: null },
    319: { sign: "Aquarius", degree: 19, en: "A Forest Fire Quenched", ja: null },
    320: { sign: "Aquarius", degree: 20, en: "A Large White Cross-Dominating the Landscape, Stands Alone on the Top of a Hill", ja: null },
    321: { sign: "Aquarius", degree: 21, en: "A Woman, Formerly a Slave to Convention, Finds a New Way of Self-Expression", ja: null },
    322: { sign: "Aquarius", degree: 22, en: "A Rug Placed on the Floor for Children to Play", ja: null },
    323: { sign: "Aquarius", degree: 23, en: "A Big Bear Sitting Down and Waving All Its Paws", ja: null },
    324: { sign: "Aquarius", degree: 24, en: "A Man Turning His Back on His Emotions and Studying Nature Alone", ja: null },
    325: { sign: "Aquarius", degree: 25, en: "A Butterfly Made Perfect by a Dart Through It", ja: null },
    326: { sign: "Aquarius", degree: 26, en: "A Big Bear Sitting Down and Waving All Its Paws", ja: null },
    327: { sign: "Aquarius", degree: 27, en: "A Train Entering a Tunnel", ja: null },
    328: { sign: "Aquarius", degree: 28, en: "A Harvest Moon Illuminates a Clear Autumnal Sky", ja: null },
    329: { sign: "Aquarius", degree: 29, en: "A Tree Felled and Sawed to Ensure a Supply of Wood for the Winter", ja: null },
    330: { sign: "Aquarius", degree: 30, en: "A Butterfly with the Left Wing More Perfectly Formed", ja: null },
    331: { sign: "Pisces", degree: 1, en: "A Public Market", ja: null },
    332: { sign: "Pisces", degree: 2, en: "A Squirrel Hiding from Hunters", ja: null },
    333: { sign: "Pisces", degree: 3, en: "A Petrified Forest", ja: null },
    334: { sign: "Pisces", degree: 4, en: "A Girl Blowing a Bugle", ja: null },
    335: { sign: "Pisces", degree: 5, en: "An Officer Instructing His Men Before a Simulated Battle Practice", ja: null },
    336: { sign: "Pisces", degree: 6, en: "A Church Bazaar", ja: null },
    337: { sign: "Pisces", degree: 7, en: "Illumined by a Ray of Light, a Large Cross Lies on Rocks Surrounded by the Sea", ja: null },
    338: { sign: "Pisces", degree: 8, en: "A Girl Blowing a Bugle", ja: null },
    339: { sign: "Pisces", degree: 9, en: "A Master Instructing His Disciple", ja: null },
    340: { sign: "Pisces", degree: 10, en: "An Aviator in the Clouds", ja: null },
    341: { sign: "Pisces", degree: 11, en: "Men Travelling a Narrow Path, Seeking Illumination", ja: null },
    342: { sign: "Pisces", degree: 12, en: "An Immigrant Enters a New Country", ja: null },
    343: { sign: "Pisces", degree: 13, en: "A Widow's Past Is Brought to Light", ja: null },
    344: { sign: "Pisces", degree: 14, en: "Slave Girls Bring Costly Gifts to Their Master's Wedding", ja: null },
    345: { sign: "Pisces", degree: 15, en: "A Bat Flying in the Twilight", ja: null },
    346: { sign: "Pisces", degree: 16, en: "A Master Instructing His Disciple", ja: null },
    347: { sign: "Pisces", degree: 17, en: "A Volunteer Church Choir Singing Religious Hymns", ja: null },
    348: { sign: "Pisces", degree: 18, en: "A Fertile Garden Under the Full Moon", ja: null },
    349: { sign: "Pisces", degree: 19, en: "A Woman Reading Tea Leaves", ja: null },
    350: { sign: "Pisces", degree: 20, en: "A Table Set for an Evening Meal", ja: null },
    351: { sign: "Pisces", degree: 21, en: "A Little White Lamb, a Child and a Chinese Servant", ja: null },
    352: { sign: "Pisces", degree: 22, en: "A Prima Donna Singing", ja: null },
    353: { sign: "Pisces", degree: 23, en: "A Petrified Forest", ja: null },
    354: { sign: "Pisces", degree: 24, en: "A Youth Holds a Lighted Candle in a Devotional Ritual", ja: null },
    355: { sign: "Pisces", degree: 25, en: "A Church Bazaar", ja: null },
    356: { sign: "Pisces", degree: 26, en: "A Parade of Bathing Beauties Before Large Beach Crowds", ja: null },
    357: { sign: "Pisces", degree: 27, en: "A Harvest Moon Illuminates a Clear Autumnal Sky", ja: null },
    358: { sign: "Pisces", degree: 28, en: "A Fertile Garden Under the Full Moon", ja: null },
    359: { sign: "Pisces", degree: 29, en: "Light Breaking into Many Colors as It Passes Through a Prism", ja: null },
    360: { sign: "Pisces", degree: 30, en: "A Majestic Rock Formation Resembling a Face Is Idealized by a Boy Who Considers It a Sign of His Future Greatness", ja: null },
  };
});
